# CircleCI config in oreder tu build/test and deploy this project
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo/src

    steps:
      - checkout:
          path: ~/repo
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo/src

    steps:
      - checkout:
          path: ~/repo
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Deploy using gh-pages!
      - run:
          name: "Deploying to http://espipj.github.io/Hacktoberfest"
          command: |
            node deploy-gh-pages.js ${GTK}

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy
